# Generated by Django 2.2 on 2019-12-08 05:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='booked_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 8, 5, 42, 19, 727911, tzinfo=utc)),
        ),
    ]
