# Generated by Django 2.2 on 2019-12-18 04:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20191208_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='check_out_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='booked_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 18, 4, 21, 50, 888226, tzinfo=utc)),
        ),
    ]
