# Generated by Django 2.2 on 2019-12-18 04:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20191218_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='booked_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 18, 4, 22, 12, 104264, tzinfo=utc)),
        ),
    ]
