# Generated by Django 2.2 on 2019-12-18 05:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_auto_20191218_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='booked_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 18, 5, 21, 14, 897744, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='check_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='check_out_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
