# Generated by Django 2.2 on 2019-12-19 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation', '0011_auto_20191218_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_id', models.CharField(max_length=20)),
                ('meal_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Roomservice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mealbook', to='reservation.Meal')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomservice', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
