# Generated by Django 2.2 on 2019-12-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0013_auto_20191219_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomservice',
            name='meal_rate',
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_rate',
            field=models.FloatField(default=30.0),
        ),
    ]
