# Generated by Django 2.2 on 2019-12-19 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0014_auto_20191219_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomservice',
            name='meal_rate',
            field=models.ForeignKey(default=30, on_delete=django.db.models.deletion.CASCADE, related_name='mealrate', to='reservation.Meal'),
            preserve_default=False,
        ),
    ]
