# Generated by Django 2.2 on 2019-12-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0015_roomservice_meal_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomservice',
            name='meal_rate',
        ),
        migrations.AddField(
            model_name='roomservice',
            name='delivery_time',
            field=models.CharField(default='Morning', max_length=64),
            preserve_default=False,
        ),
    ]
